version: "3.0"

services:
    project-zomboid:
        image: cyrale/project-zomboid
        restart: unless-stopped
        environment:
            SERVER_NAME: "aruezombi"
            ADMIN_PASSWORD: "*******"
        ports:
            - "8766:8766/udp"
            - "8767:8767/udp"
            - "16261:16261/udp"
            - "16262-16272:16262-16272"
            - "27015:27015"
        volumes:
            - ./server-data:/server-data