version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
        MOTD: "Welcome to Aruecraft"
        EULA: "TRUE"
        ENABLE_RCON: "true"
        RCON_PASSWORD: ${RCON_PASSWORD}
        RCON_PORT: 28016
    restart: always
    tty: true
    stdin_open: true
    volumes:
        - ${HOME}/data/minecraft:/data
